_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.16
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 61
            "4": 3.7.16
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
base_filters:
    value: 32
batch_size:
    value: 8
depth:
    value: 3
dropout_rate:
    value: 0.10899035794816855
lr:
    value: 4.0421205624297427e-05
